"""drop wx subscription tables

Revision ID: 8166a264ac27
Revises: a5d985df1063
Create Date: 2026-09-11 23:03:32.080716

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = '8166a264ac27'
down_revision: str | None = 'a5d985df1063'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wx_mp_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_mp_accounts_account_id'))

    op.drop_table('wx_mp_accounts')
    with op.batch_alter_table('wx_pending_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_pending_articles_account_id'))
        batch_op.drop_index(batch_op.f('ix_wx_pending_articles_created_at'))

    op.drop_table('wx_pending_articles')
    with op.batch_alter_table('wx_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_account_id'))
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_chat_id'))
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_user_id'))

    op.drop_table('wx_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('delivery_mode', sa.VARCHAR(length=16), nullable=False),
    sa.Column('output_types', sqlite.JSON(), nullable=False),
    sa.Column('last_article_time', sa.BIGINT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wx_mp_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name=op.f('uq_wx_sub_user_account'))
    )
    with op.batch_alter_table('wx_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_account_id'), ['account_id'], unique=False)

    op.create_table('wx_pending_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('doc_url', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('article_time', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wx_pending_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_pending_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_pending_articles_account_id'), ['account_id'], unique=False)

    op.create_table('wx_mp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('mp_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_synckey', sa.BIGINT(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wx_mp_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_mp_accounts_account_id'), ['account_id'], unique=1)

    # ### end Alembic commands ###
