"""wx subscription tracking tables

Revision ID: a5d985df1063
Revises: 5c2e97f0a1b8
Create Date: 2026-09-11 06:47:49.494580

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a5d985df1063'
down_revision: str | None = '5c2e97f0a1b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_mp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('mp_name', sa.String(length=128), nullable=False),
    sa.Column('last_synckey', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wx_mp_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_mp_accounts_account_id'), ['account_id'], unique=True)

    op.create_table('wx_pending_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('doc_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('article_time', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wx_pending_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_pending_articles_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_pending_articles_created_at'), ['created_at'], unique=False)

    op.create_table('wx_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('delivery_mode', sa.String(length=16), nullable=False),
    sa.Column('output_types', sa.JSON(), nullable=False),
    sa.Column('last_article_time', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wx_mp_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', name='uq_wx_sub_user_account')
    )
    with op.batch_alter_table('wx_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wx_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wx_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_chat_id'))
        batch_op.drop_index(batch_op.f('ix_wx_subscriptions_account_id'))

    op.drop_table('wx_subscriptions')
    with op.batch_alter_table('wx_pending_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_pending_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_wx_pending_articles_account_id'))

    op.drop_table('wx_pending_articles')
    with op.batch_alter_table('wx_mp_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wx_mp_accounts_account_id'))

    op.drop_table('wx_mp_accounts')
    # ### end Alembic commands ###
